######################################
#         Permissions Nodes          #
######################################
#
# Toutes les commande: spatium.*
#
# /bifle --> spatium.bifle
# /fakejoin --> spatium.fakejoin
# /fakeleft --> spatium.fakeleft
# /invi --> spatium.invi
# /maintenance --> spatium.maintenance
# /poke --> spatium.poke & spatium.poke.nocountdown
# /sban --> spatium.sban
# /sbanuuid --> spatium.banuuid
# /skick --> spatium.skick
# /smute -- spatium.smute
# /sreload --> spatium.sreload
# /sunban --> spatium.sunban
# /sunbanuuid --> spatium.sunbanuuid
# /sunmute --> spatium.sunmute
# /uuid --> spatium.uuid
# /sbank --> spatium.sbank.get
#		 --> spatium.sbank.add
#		 --> spatium.sbank.remove
# /gravitygun --> spatium.gravitygun
# /day --> spatium.day
# /night --> spatium.night
# /sun --> spatium.sun
# /rain --> spatium.rain
#
######################################
#             Config                 #
######################################
# liste des personnes autoris√©s a faire /op et /deop
OPAuth:
- putPlayerPseudoHere